### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Pthread-Create** [tomalla5120x/gruntz#1]
I found your repo while searching stuff because i'm looking into recreating gruntz on unity.
do you have discord I could try to help you with this project if you want.

Vextex Fux#3365

**Comment by tomalla5120x** [comment]
Hop on https://gooroosgruntz.proboards.com/ and join our Discord at https://gooroosgruntz.proboards.com/thread/2870/gruntz-chat-on-discord :) Originally the Discord was solely dedicated to one project but it grew and became a de facto community hub. There's also my blog at http://datashenanigans.pl/ if you ever want to know some details on file formats used by Gruntz or other technical details. Cheers
